name: Ejecutar script y actualizar archivo en OneDrive

on:
  schedule:
    - cron: '0 * * * *'   # Se ejecuta cada hora (UTC)
  workflow_dispatch:

jobs:
  run-and-update:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      EXCEL_FILE_PATH: ${{ secrets.EXCEL_FILE_PATH }}  # Asegúrate de que tenga un valor real, por ejemplo, "Copìa_Portes.xlsx"
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      # Descargar el artefacto del archivo Excel (si existe)
      - name: Download previous Excel artifact
        uses: actions/download-artifact@v2
        with:
          name: PortesExcel
          path: .
        continue-on-error: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de actualización del Excel
        run: python main.py

      # Subir el archivo actualizado como artefacto para persistencia
      - name: Upload updated Excel artifact
        uses: actions/upload-artifact@v2
        with:
          name: PortesExcel
          path: ${{ env.EXCEL_FILE_PATH }}

      - name: Leer archivo actualizado y codificar en base64
        id: encode_file
        run: |
          base64 "${{ env.EXCEL_FILE_PATH }}" > encoded.txt
          tr -d '\n' < encoded.txt > encoded_single.txt
          cat encoded_single.txt
      - name: Crear payload JSON
        run: |
          printf '{"updated_file": "' > payload.json
          cat encoded_single.txt >> payload.json
          printf '"}' >> payload.json
          cat payload.json
      - name: Enviar archivo actualizado a Power Automate
        run: |
          curl -X POST "https://TU_URL_POWER_AUTOMATE" \
            -H "Content-Type: application/json" \
            --data-binary "@payload.json"
