name: Ejecutar script y actualizar archivo en OneDrive

on:
  schedule:
    - cron: '0 * * * *'   # Se ejecuta cada hora (UTC)
  workflow_dispatch:

jobs:
  run-and-update:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      EXCEL_FILE_PATH: ${{ secrets.EXCEL_FILE_PATH }}
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de actualización del Excel
        run: python main.py

      - name: Leer archivo actualizado y codificar en base64
        id: encode_file
        run: |
          base64 "${{ env.EXCEL_FILE_PATH }}" > encoded.txt
          tr -d '\n' < encoded.txt > encoded_single.txt
          cat encoded_single.txt
      - name: Crear payload JSON
        run: |
          printf '{"updated_file": "' > payload.json
          cat encoded_single.txt >> payload.json
          printf '"}' >> payload.json
          cat payload.json
      - name: Enviar archivo actualizado a Power Automate
        run: |
          UPDATED_CONTENT=$(cat payload.json)
          curl -X POST "https://prod-120.westeurope.logic.azure.com:443/workflows/77fbcf15c8a643bbb3fd225993761713/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=j4g0ozXaCTIl3B-Zw6MI8JxdsBYoZsOrlrSB88KQwfs" \
            -H "Content-Type: application/json" \
            --data-binary "@payload.json"
