name: Ejecutar script y actualizar archivo en OneDrive

on:
  schedule:
    - cron: '0 * * * *'   # Se ejecuta cada hora (UTC)
  workflow_dispatch:

jobs:
  run-and-update:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      EXCEL_FILE_PATH: ${{ secrets.EXCEL_FILE_PATH }}  # Ejemplo: "Portes.xlsx"
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: List files in directory (pre-run)
        run: ls -la

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de actualización del Excel
        run: python main.py

      - name: List files in directory (post-run)
        run: ls -la

      # Enviar el archivo actualizado directamente a Power Automate
      - name: Enviar archivo actualizado a Power Automate
        run: |
          curl -X POST "https://TU_URL_POWER_AUTOMATE" \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@${{ env.EXCEL_FILE_PATH }}"
